Added Partition activate and shutdown support
ansible-aix/ansible-power-hmc pull request #30
Opened 2021-03-15 14:40 UTC by naveenkandakur

2021-03-17 06:54 UTC, AnilVijayan commented on plugins/module_utils/hmc_rest_client.py
> +        return lparProfiles_root
Is it not better to return the profiles list instead of entire dom?

2021-03-17 06:54 UTC, AnilVijayan commented on plugins/modules/powervm_lpar_instance.py
> +    - "Or Poweron/Activate specified AIX/Linux or IBMi partition with specified configuration details on specified system"
Poweron/Activate specified AIX/Linux or IBMi partition with provided configuration on the mentioned system

2021-03-17 06:54 UTC, AnilVijayan commented on plugins/module_utils/hmc_rest_client.py
> +            return None, None
why return tuple?

2021-03-17 06:54 UTC, AnilVijayan commented on plugins/modules/powervm_lpar_instance.py
> +            module.fail_json(msg="Given Logical Partition is not present on given system or user is not assigned with required resource roles")
given system = system

2021-03-17 06:54 UTC, AnilVijayan commented on plugins/modules/powervm_lpar_instance.py
> +            module.fail_json(msg="There are no Logical Partitions present on given system or user is not assigned with required resource roles")
user is not assigned with required resource roles - can be removed

2021-03-19 09:06 UTC, AnilVijayan commented on plugins/modules/powervm_lpar_instance.py
> +            module.fail_json(msg="There are no Logical Partitions present on a system")
There are no Logical Partitions present on the system

2021-03-19 09:06 UTC, AnilVijayan commented on plugins/modules/powervm_lpar_instance.py
> +            module.fail_json(msg="Provided Logical Partition is not present on a system")
same as above

2021-03-19 09:06 UTC, AnilVijayan commented on plugins/modules/powervm_lpar_instance.py
> +            module.fail_json(msg="Provided Logical Partition Profile is not present on a logical Partition")
same as above

2021-03-19 09:08 UTC, AnilVijayan requested changes
Please address the mentioned changes

2021-03-19 16:17 UTC, naveenkandakur commented
> 
> 
> Please address the mentioned changes

Addressed.

2021-03-19 16:18 UTC, naveenkandakur commented
> 
> 
> > Please address the mentioned changes
> 
> Addressed.

2021-03-21 15:45 UTC, AnilVijayan approved these changes

2021-03-21 15:45 UTC, merged